config/routes.rb
SiGNo::Application.routes.draw do

  namespace :experiments do
    resources :dblp, only: [:index] do
      collection do
        get ':group', to: 'dblp#index', as: :group
        get ':group/next_author', to: 'dblp#next_author', as: :next_author
        get ':group/:url', to: 'dblp#show', as: :author
        post ':group/:url/update_author', to: 'dblp#update', as: :update_author
      end
    end
  end

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "SiGNo"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js'
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") SiGNo
          .container.nav-collapse
            %ul.nav
              %li= link_to "DBLP", experiments_dblp_index_path

    .container-fluid
      .row-fluid
        .span12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; SiGNo 2013